Event_Management_System/Controllers/EventController.cs
using Event_Management_System.Contexts;
using Event_Management_System.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Event_Management_System.Controllers;
public class EventController : Controller
{
    private readonly EventDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;

    public EventController(EventDbContext context, UserManager<ApplicationUser> userManager)
    {
        _context = context;
        this._userManager = userManager;
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        var events = _context.Events
            .Include(e => e.Organizer)
            .Include(e => e.EventCategory)
            .ToList();

        return View(events);
    }

    public IActionResult Create()
    {
        var categories = _context.Categories.ToList();
        ViewData["Categories"] = categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Event @event)
    {
        if (ModelState.IsValid)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            @event.OrganizerId = currentUser.Id;

            _context.Events.Add(@event);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        var categories = _context.Categories.ToList();
        ViewData["Categories"] = categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
        return View(@event);
    }


    public IActionResult Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @event = _context.Events
            .Include(e => e.Organizer)
            .Include(e => e.EventCategory)
            .FirstOrDefault(e => e.Id == id);

        if (@event == null)
        {
            return NotFound();
        }

        ViewBag.Organizers = _context.Users.ToList();

        // Convert the list of Category objects to a list of SelectListItem
        ViewBag.Categories = _context.Categories
            .Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name })
            .ToList();

        return View(@event);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(int id, Event @event)
    {
        if (id != @event.Id)
        {
            return NotFound();
        }
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (ModelState.IsValid)
        {
            try
            {
                @event.OrganizerId = userId;
                _context.Events.Update(@event);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EventExists(@event.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        ViewBag.Organizers = _context.Users.ToList();

        // Convert the list of Category objects to a list of SelectListItem
        ViewBag.Categories = _context.Categories
            .Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name })
            .ToList();

        return View(@event);
    }


    public IActionResult Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @event = _context.Events
            .Include(e => e.Organizer)
            .Include(e => e.EventCategory)
            .FirstOrDefault(e => e.Id == id);

        if (@event == null)
        {
            return NotFound();
        }

        return View(@event);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
        var @event = _context.Events.Find(id);
        _context.Events.Remove(@event);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var @event = _context.Events
            .Include(e => e.Organizer)
            .Include(e => e.EventCategory)
            .Include(e => e.Participants)
            .FirstOrDefault(e => e.Id == id);

        if (@event == null)
        {
            return NotFound();
        }

        var currentUser = _userManager.GetUserAsync(User).Result;
        ViewBag.HasParticipated = _context.Participants.Any(p => p.EventId == id && p.UserId == currentUser.Id);

        return View(@event);
    }

    private bool EventExists(int id)
    {
        return _context.Events.Any(e => e.Id == id);
    }
}

Event_Management_System/Controllers/PrivatController.cs
using Event_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Event_Management_System.Controllers;
public class PrivatController : Controller
{
    private readonly HttpClient _client;

    public PrivatController()
    {
        _client = new HttpClient();
    }

    public async Task<IActionResult> GetExchangeRates()
    {
        var response = await _client.GetAsync("https://api.privatbank.ua/p24api/exchange_rates?date=01.12.2014");

        if (!response.IsSuccessStatusCode)
        {
            return View("Error", "Failed to fetch exchange rates.");
        }

        var ratesJson = await response.Content.ReadAsStringAsync();
        var rates = JsonConvert.DeserializeObject<Privat24Rates>(ratesJson);

        return View("PrivatRates", rates);
    }
}

Event_Management_System/Views/Shared/DisplayTemplates.cshtml
@model DateTime?
@if (Model.HasValue)
{
    @Model.Value.ToString("dd/MM/yyyy")
}

Event_Management_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Events</title>
    <link rel="stylesheet" href="~/css/Theme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Real_Estate_Laba.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Privat" asp-action="GetExchangeRates">Get Exchange Rates</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>